### ISSUE TITLE
有类似umijs的block功能吗。

### ISSUE THREAD

**Issue by AimLuo** [forsigner/dahlia#1]
大概过了一遍文档，好像没发现类似umijs的block功能。

- [ ] 或者有什么好的解决方案？

- [ ] 引入antd大多数人可能会需要。
- [ ] immutable 有没有必要

确实现有的redux的异步数据存储方案过于繁琐

**Comment by forsigner** [comment]
- block 是 umi 特有的方案，暂时不评价，可能直接用组件复用就可以
- 可以修改配置文件 `dahlia.config.ts` 来支持 antd，这个今晚补充文档
- 这里的 immutable 是指？

**Comment by AimLuo** [comment]
immutable不可变数据类型。因为JavaScript的object是引用类型，所以用了这个保证数据不会被更改。

**Comment by forsigner** [comment]
这个我知道，dahlia 貌似没强制 immutable

**Comment by forsigner** [comment]
关于如何使用 antd: https://dahlia.js.org/docs/webpack/basic
